[[session]]
name = "tmux config"
path = "~/.config/tmux/"
startup_command = "nvim tmux.conf"

[[session]]
name = "dotfiles config"
path = "~/dotfiles/"
startup_command = "nvim ."

[[session]]
name = "dev"
path = "~/software-development/"
startup_command = "l"

[[session]]
name = "monitoring"
path = "~/"
startup_command = "btop"
